// Code generated by mss-protoc-gen. DO NOT EDIT.

import { TaskDetail } from "../../../gen/ui/task/TaskDetail";

export default function TaskDetailPage({ params }: { params: { id: string } }) {
  return (<main style={{ maxWidth: 640, margin: "2rem auto", fontFamily: "system-ui" }}><TaskDetail id={params.id} /></main>);
}
