// Code generated by mss-protoc-gen. DO NOT EDIT.

import { TaskDetail } from "../../../gen/ui/task/TaskDetail";
import { Page } from "../../../lib/widgets";

export default function TaskDetailPage({ params }: { params: { id: string } }) {
  return (<Page title="Task"><TaskDetail id={params.id} /></Page>);
}
