// Code generated by mss-protoc-gen. DO NOT EDIT.

import { ProjectForm } from "../../../gen/ui/project/ProjectForm";
import { Page } from "../../../lib/widgets";

export default function NewProjectPage() {
  return (<Page title="New Project"><ProjectForm /></Page>);
}
