// Code generated by mss-protoc-gen. DO NOT EDIT.

import { ProjectForm } from "../../../../gen/ui/project/ProjectForm";
import { Page } from "../../../../lib/widgets";

export default function EditProjectPage({ params }: { params: { id: string } }) {
  return (<Page title="Edit Project"><ProjectForm id={params.id} /></Page>);
}
