// Code generated by mss-protoc-gen. DO NOT EDIT.

import { ProjectForm } from "../../../../gen/ui/project/ProjectForm";

export default function EditProjectPage({ params }: { params: { id: string } }) {
  return (<main style={{ maxWidth: 640, margin: "2rem auto", fontFamily: "system-ui" }}><h1>Edit Project</h1><ProjectForm id={params.id} /></main>);
}
