# Code generated by mss-protoc-gen. DO NOT EDIT.
from __future__ import annotations
from dataclasses import dataclass
from typing import Protocol
from pydantic import BaseModel
from app.dto.project import ProjectDTO

@dataclass
class ListProjectsInput:
    pass


@dataclass
class ListProjectsByCursorInput:
    limit: int
    after_id: str


@dataclass
class GetProjectInput:
    id: str


@dataclass
class CreateProjectInput:
    name: str
    goal: str
    status: str
    progress: int
    repo_url: str
    kb_node: str


@dataclass
class UpdateProjectInput:
    id: str
    name: str
    goal: str
    status: str
    progress: int
    repo_url: str
    kb_node: str


@dataclass
class DeleteProjectInput:
    id: str


class ProjectServiceUsecase(Protocol):
    def list_projects(self, inp: ListProjectsInput) -> list[ProjectDTO]: ...
    def list_projects_by_cursor(self, inp: ListProjectsByCursorInput) -> list[ProjectDTO]: ...
    def get_project(self, inp: GetProjectInput) -> ProjectDTO | None: ...
    def create_project(self, inp: CreateProjectInput) -> ProjectDTO | None: ...
    def update_project(self, inp: UpdateProjectInput) -> ProjectDTO | None: ...
    def delete_project(self, inp: DeleteProjectInput) -> None: ...
