# Code generated by mss-protoc-gen. DO NOT EDIT.
from __future__ import annotations
from dataclasses import dataclass
from typing import Protocol
from app.dto.task import TaskDTO

@dataclass
class ListTasksInput:
    pass


@dataclass
class ListTasksByCursorInput:
    limit: int
    after_id: str


@dataclass
class GetTaskInput:
    id: str


@dataclass
class CreateTaskInput:
    project_id: str
    title: str
    status: str
    note: str


@dataclass
class UpdateTaskInput:
    id: str
    project_id: str
    title: str
    status: str
    note: str


@dataclass
class DeleteTaskInput:
    id: str


class TaskServiceUsecase(Protocol):
    def list_tasks(self, inp: ListTasksInput) -> list[TaskDTO]: ...
    def list_tasks_by_cursor(self, inp: ListTasksByCursorInput) -> list[TaskDTO]: ...
    def get_task(self, inp: GetTaskInput) -> TaskDTO | None: ...
    def create_task(self, inp: CreateTaskInput) -> TaskDTO | None: ...
    def update_task(self, inp: UpdateTaskInput) -> TaskDTO | None: ...
    def delete_task(self, inp: DeleteTaskInput) -> None: ...
