# Code generated by mss-protoc-gen. DO NOT EDIT.
from __future__ import annotations
from dataclasses import dataclass
from typing import Protocol
from app.dto.user_setting import UserSettingDTO

@dataclass
class GetMySettingsInput:
    pass


@dataclass
class UpsertMySettingsInput:
    github_pat: str
    kb_repo: str
    kb_branch: str


class UserSettingServiceUsecase(Protocol):
    def get_my_settings(self, inp: GetMySettingsInput) -> UserSettingDTO | None: ...
    def upsert_my_settings(self, inp: UpsertMySettingsInput) -> UserSettingDTO | None: ...
