# Code generated by mss-protoc-gen. DO NOT EDIT.
from __future__ import annotations
from dataclasses import dataclass
from typing import Protocol
from pydantic import BaseModel
from app.dto.work_log import WorkLogDTO

@dataclass
class ListWorkLogsInput:
    pass


@dataclass
class ListWorkLogsByCursorInput:
    limit: int
    after_id: str


@dataclass
class GetWorkLogInput:
    id: str


@dataclass
class CreateWorkLogInput:
    project_id: str
    summary: str
    minutes: int
    source: str


@dataclass
class UpdateWorkLogInput:
    id: str
    project_id: str
    summary: str
    minutes: int
    source: str


@dataclass
class DeleteWorkLogInput:
    id: str


class WorkLogServiceUsecase(Protocol):
    def list_work_logs(self, inp: ListWorkLogsInput) -> list[WorkLogDTO]: ...
    def list_work_logs_by_cursor(self, inp: ListWorkLogsByCursorInput) -> list[WorkLogDTO]: ...
    def get_work_log(self, inp: GetWorkLogInput) -> WorkLogDTO | None: ...
    def create_work_log(self, inp: CreateWorkLogInput) -> WorkLogDTO | None: ...
    def update_work_log(self, inp: UpdateWorkLogInput) -> WorkLogDTO | None: ...
    def delete_work_log(self, inp: DeleteWorkLogInput) -> None: ...
