// Code generated by mss-protoc-gen. DO NOT EDIT.

import { WorkLogForm } from "../../../gen/ui/work_log/WorkLogForm";

export default function NewWorkLogPage() {
  return (<main style={{ maxWidth: 640, margin: "2rem auto", fontFamily: "system-ui" }}><h1>New WorkLog</h1><WorkLogForm /></main>);
}
