// Code generated by mss-protoc-gen. DO NOT EDIT.

import { WorkLogForm } from "../../../gen/ui/work_log/WorkLogForm";
import { Page } from "../../../lib/widgets";

export default function NewWorkLogPage() {
  return (<Page title="New WorkLog"><WorkLogForm /></Page>);
}
