// Code generated by mss-protoc-gen. DO NOT EDIT.

import { TaskForm } from "../../../../gen/ui/task/TaskForm";
import { Page } from "../../../../lib/widgets";

export default function EditTaskPage({ params }: { params: { id: string } }) {
  return (<Page title="Edit Task"><TaskForm id={params.id} /></Page>);
}
