// Code generated by mss-protoc-gen. DO NOT EDIT.

import { TaskForm } from "../../../../gen/ui/task/TaskForm";

export default function EditTaskPage({ params }: { params: { id: string } }) {
  return (<main style={{ maxWidth: 640, margin: "2rem auto", fontFamily: "system-ui" }}><h1>Edit Task</h1><TaskForm id={params.id} /></main>);
}
