// Code generated by mss-protoc-gen. DO NOT EDIT.

import { ProjectDetail } from "../../../gen/ui/project/ProjectDetail";

export default function ProjectDetailPage({ params }: { params: { id: string } }) {
  return (<main style={{ maxWidth: 640, margin: "2rem auto", fontFamily: "system-ui" }}><ProjectDetail id={params.id} /></main>);
}
