// Code generated by mss-protoc-gen. DO NOT EDIT.

import { ProjectDetail } from "../../../gen/ui/project/ProjectDetail";
import { Page } from "../../../lib/widgets";

export default function ProjectDetailPage({ params }: { params: { id: string } }) {
  return (<Page title="Project"><ProjectDetail id={params.id} /></Page>);
}
