// Code generated by mss-protoc-gen. DO NOT EDIT.

import Link from "next/link";
import { ProjectList } from "../../gen/ui/project/ProjectList";
import { Page } from "../../lib/widgets";

export default function ProjectsPage() {
  return (<Page title="Projects" actions={<Link href="/projects/new">+ New</Link>}><ProjectList /></Page>);
}
