// Code generated by mss-protoc-gen. DO NOT EDIT.

import { ProjectList } from "../../gen/ui/project/ProjectList";

export default function ProjectsPage() {
  return (<main style={{ maxWidth: 640, margin: "2rem auto", fontFamily: "system-ui" }}><h1>Projects</h1><ProjectList /></main>);
}
