// Code generated by mss-protoc-gen. DO NOT EDIT.

import { WorkLogDetail } from "../../../gen/ui/work_log/WorkLogDetail";

export default function WorkLogDetailPage({ params }: { params: { id: string } }) {
  return (<main style={{ maxWidth: 640, margin: "2rem auto", fontFamily: "system-ui" }}><WorkLogDetail id={params.id} /></main>);
}
