// Code generated by mss-protoc-gen. DO NOT EDIT.

import { WorkLogDetail } from "../../../gen/ui/work_log/WorkLogDetail";
import { Page } from "../../../lib/widgets";

export default function WorkLogDetailPage({ params }: { params: { id: string } }) {
  return (<Page title="WorkLog"><WorkLogDetail id={params.id} /></Page>);
}
