# Code generated by mss-protoc-gen. DO NOT EDIT.
from __future__ import annotations
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from app.usecase.project_usecase_interface import (
    ListProjectsInput,
    ListProjectsByCursorInput,
    GetProjectInput,
    CreateProjectInput,
    UpdateProjectInput,
    DeleteProjectInput,
    ProjectServiceUsecase,
)
from app.domain.repository.project_repository import (
    ProjectNotFoundError,
    ProjectAlreadyExistsError,
)

class CreateProjectBody(BaseModel):
    name: str
    goal: str
    status: str
    progress: int
    repo_url: str
    kb_node: str


class UpdateProjectBody(BaseModel):
    name: str
    goal: str
    status: str
    progress: int
    repo_url: str
    kb_node: str


def new_project_router(uc: ProjectServiceUsecase) -> APIRouter:
    router = APIRouter()

    @router.get("/api/projects")
    def list_projects(
    ):
        try:
            result = uc.list_projects(
                ListProjectsInput(
                )
            )
        except ProjectNotFoundError:
            raise HTTPException(status_code=404, detail="not found")
        except ProjectAlreadyExistsError:
            raise HTTPException(status_code=409, detail="already exists")
        except ValueError as ex:
            raise HTTPException(status_code=400, detail=str(ex))
        return [d.to_dict() for d in result]

    @router.get("/api/projects/cursor")
    def list_projects_by_cursor(
        limit: int | None = None,
        after_id: str | None = None,
    ):
        try:
            result = uc.list_projects_by_cursor(
                ListProjectsByCursorInput(
                    limit=limit,
                    after_id=after_id,
                )
            )
        except ProjectNotFoundError:
            raise HTTPException(status_code=404, detail="not found")
        except ProjectAlreadyExistsError:
            raise HTTPException(status_code=409, detail="already exists")
        except ValueError as ex:
            raise HTTPException(status_code=400, detail=str(ex))
        return [d.to_dict() for d in result]

    @router.get("/api/projects/{id}")
    def get_project(
        id: str,
    ):
        try:
            result = uc.get_project(
                GetProjectInput(
                    id=id,
                )
            )
        except ProjectNotFoundError:
            raise HTTPException(status_code=404, detail="not found")
        except ProjectAlreadyExistsError:
            raise HTTPException(status_code=409, detail="already exists")
        except ValueError as ex:
            raise HTTPException(status_code=400, detail=str(ex))
        if result is None:
            raise HTTPException(status_code=404, detail="not found")
        return result.to_dict()

    @router.post("/api/projects", status_code=201)
    def create_project(
        body: CreateProjectBody,
    ):
        try:
            result = uc.create_project(
                CreateProjectInput(
                    name=body.name,
                    goal=body.goal,
                    status=body.status,
                    progress=body.progress,
                    repo_url=body.repo_url,
                    kb_node=body.kb_node,
                )
            )
        except ProjectNotFoundError:
            raise HTTPException(status_code=404, detail="not found")
        except ProjectAlreadyExistsError:
            raise HTTPException(status_code=409, detail="already exists")
        except ValueError as ex:
            raise HTTPException(status_code=400, detail=str(ex))
        if result is None:
            raise HTTPException(status_code=404, detail="not found")
        return result.to_dict()

    @router.patch("/api/projects/{id}")
    def update_project(
        id: str,
        body: UpdateProjectBody,
    ):
        try:
            result = uc.update_project(
                UpdateProjectInput(
                    id=id,
                    name=body.name,
                    goal=body.goal,
                    status=body.status,
                    progress=body.progress,
                    repo_url=body.repo_url,
                    kb_node=body.kb_node,
                )
            )
        except ProjectNotFoundError:
            raise HTTPException(status_code=404, detail="not found")
        except ProjectAlreadyExistsError:
            raise HTTPException(status_code=409, detail="already exists")
        except ValueError as ex:
            raise HTTPException(status_code=400, detail=str(ex))
        if result is None:
            raise HTTPException(status_code=404, detail="not found")
        return result.to_dict()

    @router.delete("/api/projects/{id}", status_code=204)
    def delete_project(
        id: str,
    ):
        try:
            result = uc.delete_project(
                DeleteProjectInput(
                    id=id,
                )
            )
        except ProjectNotFoundError:
            raise HTTPException(status_code=404, detail="not found")
        except ProjectAlreadyExistsError:
            raise HTTPException(status_code=409, detail="already exists")
        except ValueError as ex:
            raise HTTPException(status_code=400, detail=str(ex))
        return None
    return router
