# Code generated by mss-protoc-gen. DO NOT EDIT.
from __future__ import annotations
from fastapi import APIRouter, HTTPException, Depends
from pydantic import BaseModel
from app.infra.tenancy import require_owner
from app.usecase.task_usecase_interface import (
    ListTasksInput,
    ListTasksByCursorInput,
    GetTaskInput,
    CreateTaskInput,
    UpdateTaskInput,
    DeleteTaskInput,
    TaskServiceUsecase,
)
from app.domain.repository.task_repository import (
    TaskNotFoundError,
    TaskAlreadyExistsError,
)

class CreateTaskBody(BaseModel):
    project_id: str
    title: str
    status: str
    note: str


class UpdateTaskBody(BaseModel):
    project_id: str
    title: str
    status: str
    note: str


def new_task_router(uc: TaskServiceUsecase) -> APIRouter:
    # @owned: 全ルートで principal を解決し contextvar に載せる(repo が current_owner() で読む)
    router = APIRouter(dependencies=[Depends(require_owner)])

    @router.get("/api/tasks")
    def list_tasks(
    ):
        try:
            result = uc.list_tasks(
                ListTasksInput(
                )
            )
        except TaskNotFoundError:
            raise HTTPException(status_code=404, detail="not found")
        except TaskAlreadyExistsError:
            raise HTTPException(status_code=409, detail="already exists")
        except ValueError as ex:
            raise HTTPException(status_code=400, detail=str(ex))
        return [d.to_dict() for d in result]

    @router.get("/api/tasks/cursor")
    def list_tasks_by_cursor(
        limit: int | None = None,
        after_id: str | None = None,
    ):
        try:
            result = uc.list_tasks_by_cursor(
                ListTasksByCursorInput(
                    limit=limit,
                    after_id=after_id,
                )
            )
        except TaskNotFoundError:
            raise HTTPException(status_code=404, detail="not found")
        except TaskAlreadyExistsError:
            raise HTTPException(status_code=409, detail="already exists")
        except ValueError as ex:
            raise HTTPException(status_code=400, detail=str(ex))
        return [d.to_dict() for d in result]

    @router.get("/api/tasks/{id}")
    def get_task(
        id: str,
    ):
        try:
            result = uc.get_task(
                GetTaskInput(
                    id=id,
                )
            )
        except TaskNotFoundError:
            raise HTTPException(status_code=404, detail="not found")
        except TaskAlreadyExistsError:
            raise HTTPException(status_code=409, detail="already exists")
        except ValueError as ex:
            raise HTTPException(status_code=400, detail=str(ex))
        if result is None:
            raise HTTPException(status_code=404, detail="not found")
        return result.to_dict()

    @router.post("/api/tasks", status_code=201)
    def create_task(
        body: CreateTaskBody,
    ):
        try:
            result = uc.create_task(
                CreateTaskInput(
                    project_id=body.project_id,
                    title=body.title,
                    status=body.status,
                    note=body.note,
                )
            )
        except TaskNotFoundError:
            raise HTTPException(status_code=404, detail="not found")
        except TaskAlreadyExistsError:
            raise HTTPException(status_code=409, detail="already exists")
        except ValueError as ex:
            raise HTTPException(status_code=400, detail=str(ex))
        if result is None:
            raise HTTPException(status_code=404, detail="not found")
        return result.to_dict()

    @router.patch("/api/tasks/{id}")
    def update_task(
        id: str,
        body: UpdateTaskBody,
    ):
        try:
            result = uc.update_task(
                UpdateTaskInput(
                    id=id,
                    project_id=body.project_id,
                    title=body.title,
                    status=body.status,
                    note=body.note,
                )
            )
        except TaskNotFoundError:
            raise HTTPException(status_code=404, detail="not found")
        except TaskAlreadyExistsError:
            raise HTTPException(status_code=409, detail="already exists")
        except ValueError as ex:
            raise HTTPException(status_code=400, detail=str(ex))
        if result is None:
            raise HTTPException(status_code=404, detail="not found")
        return result.to_dict()

    @router.delete("/api/tasks/{id}", status_code=204)
    def delete_task(
        id: str,
    ):
        try:
            uc.delete_task(
                DeleteTaskInput(
                    id=id,
                )
            )
        except TaskNotFoundError:
            raise HTTPException(status_code=404, detail="not found")
        except TaskAlreadyExistsError:
            raise HTTPException(status_code=409, detail="already exists")
        except ValueError as ex:
            raise HTTPException(status_code=400, detail=str(ex))
        return None
    return router
