# Code generated by mss-protoc-gen. DO NOT EDIT.
from __future__ import annotations
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from app.usecase.user_setting_usecase_interface import (
    GetMySettingsInput,
    UpsertMySettingsInput,
    UserSettingServiceUsecase,
)
from app.domain.repository.user_setting_repository import (
    UserSettingNotFoundError,
    UserSettingAlreadyExistsError,
)

class UpsertMySettingsBody(BaseModel):
    github_pat: str
    kb_repo: str
    kb_branch: str


def new_user_setting_router(uc: UserSettingServiceUsecase) -> APIRouter:
    # @owned: principal はアプリ横断の TenancyMiddleware が owner_scope で張る
    # (Depends/threadpool 跨ぎでは contextvar が届かないため router では設定しない)。
    router = APIRouter()

    @router.get("/api/settings")
    def get_my_settings(
    ):
        try:
            result = uc.get_my_settings(
                GetMySettingsInput(
                )
            )
        except UserSettingNotFoundError:
            raise HTTPException(status_code=404, detail="not found")
        except UserSettingAlreadyExistsError:
            raise HTTPException(status_code=409, detail="already exists")
        except ValueError as ex:
            raise HTTPException(status_code=400, detail=str(ex))
        if result is None:
            raise HTTPException(status_code=404, detail="not found")
        return result.to_dict()

    @router.put("/api/settings")
    def upsert_my_settings(
        body: UpsertMySettingsBody,
    ):
        try:
            result = uc.upsert_my_settings(
                UpsertMySettingsInput(
                    github_pat=body.github_pat,
                    kb_repo=body.kb_repo,
                    kb_branch=body.kb_branch,
                )
            )
        except UserSettingNotFoundError:
            raise HTTPException(status_code=404, detail="not found")
        except UserSettingAlreadyExistsError:
            raise HTTPException(status_code=409, detail="already exists")
        except ValueError as ex:
            raise HTTPException(status_code=400, detail=str(ex))
        if result is None:
            raise HTTPException(status_code=404, detail="not found")
        return result.to_dict()
    return router
