# Code generated by mss-protoc-gen. DO NOT EDIT.
from __future__ import annotations
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from app.usecase.work_log_usecase_interface import (
    ListWorkLogsInput,
    ListWorkLogsByCursorInput,
    GetWorkLogInput,
    CreateWorkLogInput,
    UpdateWorkLogInput,
    DeleteWorkLogInput,
    WorkLogServiceUsecase,
)
from app.domain.repository.work_log_repository import (
    WorkLogNotFoundError,
    WorkLogAlreadyExistsError,
)

class CreateWorkLogBody(BaseModel):
    project_id: str
    summary: str
    minutes: int
    source: str


class UpdateWorkLogBody(BaseModel):
    project_id: str
    summary: str
    minutes: int
    source: str


def new_work_log_router(uc: WorkLogServiceUsecase) -> APIRouter:
    router = APIRouter()

    @router.get("/api/work-logs")
    def list_work_logs(
    ):
        try:
            result = uc.list_work_logs(
                ListWorkLogsInput(
                )
            )
        except WorkLogNotFoundError:
            raise HTTPException(status_code=404, detail="not found")
        except WorkLogAlreadyExistsError:
            raise HTTPException(status_code=409, detail="already exists")
        except ValueError as ex:
            raise HTTPException(status_code=400, detail=str(ex))
        return [d.to_dict() for d in result]

    @router.get("/api/work-logs/cursor")
    def list_work_logs_by_cursor(
        limit: int | None = None,
        after_id: str | None = None,
    ):
        try:
            result = uc.list_work_logs_by_cursor(
                ListWorkLogsByCursorInput(
                    limit=limit,
                    after_id=after_id,
                )
            )
        except WorkLogNotFoundError:
            raise HTTPException(status_code=404, detail="not found")
        except WorkLogAlreadyExistsError:
            raise HTTPException(status_code=409, detail="already exists")
        except ValueError as ex:
            raise HTTPException(status_code=400, detail=str(ex))
        return [d.to_dict() for d in result]

    @router.get("/api/work-logs/{id}")
    def get_work_log(
        id: str,
    ):
        try:
            result = uc.get_work_log(
                GetWorkLogInput(
                    id=id,
                )
            )
        except WorkLogNotFoundError:
            raise HTTPException(status_code=404, detail="not found")
        except WorkLogAlreadyExistsError:
            raise HTTPException(status_code=409, detail="already exists")
        except ValueError as ex:
            raise HTTPException(status_code=400, detail=str(ex))
        if result is None:
            raise HTTPException(status_code=404, detail="not found")
        return result.to_dict()

    @router.post("/api/work-logs", status_code=201)
    def create_work_log(
        body: CreateWorkLogBody,
    ):
        try:
            result = uc.create_work_log(
                CreateWorkLogInput(
                    project_id=body.project_id,
                    summary=body.summary,
                    minutes=body.minutes,
                    source=body.source,
                )
            )
        except WorkLogNotFoundError:
            raise HTTPException(status_code=404, detail="not found")
        except WorkLogAlreadyExistsError:
            raise HTTPException(status_code=409, detail="already exists")
        except ValueError as ex:
            raise HTTPException(status_code=400, detail=str(ex))
        if result is None:
            raise HTTPException(status_code=404, detail="not found")
        return result.to_dict()

    @router.patch("/api/work-logs/{id}")
    def update_work_log(
        id: str,
        body: UpdateWorkLogBody,
    ):
        try:
            result = uc.update_work_log(
                UpdateWorkLogInput(
                    id=id,
                    project_id=body.project_id,
                    summary=body.summary,
                    minutes=body.minutes,
                    source=body.source,
                )
            )
        except WorkLogNotFoundError:
            raise HTTPException(status_code=404, detail="not found")
        except WorkLogAlreadyExistsError:
            raise HTTPException(status_code=409, detail="already exists")
        except ValueError as ex:
            raise HTTPException(status_code=400, detail=str(ex))
        if result is None:
            raise HTTPException(status_code=404, detail="not found")
        return result.to_dict()

    @router.delete("/api/work-logs/{id}", status_code=204)
    def delete_work_log(
        id: str,
    ):
        try:
            uc.delete_work_log(
                DeleteWorkLogInput(
                    id=id,
                )
            )
        except WorkLogNotFoundError:
            raise HTTPException(status_code=404, detail="not found")
        except WorkLogAlreadyExistsError:
            raise HTTPException(status_code=409, detail="already exists")
        except ValueError as ex:
            raise HTTPException(status_code=400, detail=str(ex))
        return None
    return router
