// Code generated by mss-protoc-gen. DO NOT EDIT.

import Link from "next/link";
import { WorkLogList } from "../../gen/ui/work_log/WorkLogList";
import { Page } from "../../lib/widgets";

export default function WorkLogsPage() {
  return (<Page title="WorkLogs" actions={<Link href="/work_logs/new">+ New</Link>}><WorkLogList /></Page>);
}
