// Code generated by mss-protoc-gen. DO NOT EDIT.

import { WorkLogList } from "../../gen/ui/work_log/WorkLogList";

export default function WorkLogsPage() {
  return (<main style={{ maxWidth: 640, margin: "2rem auto", fontFamily: "system-ui" }}><h1>WorkLogs</h1><WorkLogList /></main>);
}
