// Code generated by mss-protoc-gen. DO NOT EDIT.

import Link from "next/link";
import { TaskList } from "../../gen/ui/task/TaskList";
import { Page } from "../../lib/widgets";

export default function TasksPage() {
  return (<Page title="Tasks" actions={<Link href="/tasks/new">+ New</Link>}><TaskList /></Page>);
}
