// Code generated by mss-protoc-gen. DO NOT EDIT.

import { TaskList } from "../../gen/ui/task/TaskList";

export default function TasksPage() {
  return (<main style={{ maxWidth: 640, margin: "2rem auto", fontFamily: "system-ui" }}><h1>Tasks</h1><TaskList /></main>);
}
