# Code generated by mss-protoc-gen. DO NOT EDIT.
from __future__ import annotations
from dataclasses import dataclass
from app.domain.entity.project import Project


@dataclass
class ProjectDTO:
    id: str
    name: str
    goal: str
    status: str
    progress: int
    repo_url: str
    kb_node: str
    created_at_unix: int

    @classmethod
    def from_entity(cls, e: Project) -> "ProjectDTO":
        return cls(
            id=e.id,
            name=e.name,
            goal=e.goal,
            status=e.status,
            progress=e.progress,
            repo_url=e.repo_url,
            kb_node=e.kb_node,
            created_at_unix=int(e.created_at.timestamp()),
        )

    def to_dict(self) -> dict:
        return self.__dict__


def from_entities(es: list[Project]) -> list[ProjectDTO]:
    return [ProjectDTO.from_entity(e) for e in es]
