# Code generated by mss-protoc-gen. DO NOT EDIT.
from __future__ import annotations
from dataclasses import dataclass
from app.domain.entity.task import Task


@dataclass
class TaskDTO:
    id: str
    project_id: str
    title: str
    status: str
    note: str
    created_at_unix: int

    @classmethod
    def from_entity(cls, e: Task) -> "TaskDTO":
        return cls(
            id=e.id,
            project_id=e.project_id,
            title=e.title,
            status=e.status,
            note=e.note,
            created_at_unix=int(e.created_at.timestamp()),
        )

    def to_dict(self) -> dict:
        return self.__dict__


def from_entities(es: list[Task]) -> list[TaskDTO]:
    return [TaskDTO.from_entity(e) for e in es]
