# Code generated by mss-protoc-gen. DO NOT EDIT.
from __future__ import annotations
from dataclasses import dataclass
from app.domain.entity.user_setting import UserSetting


@dataclass
class UserSettingDTO:
    email: str
    github_pat_enc: str
    kb_repo: str
    kb_branch: str
    mcp_token: str
    created_at_unix: int

    @classmethod
    def from_entity(cls, e: UserSetting) -> "UserSettingDTO":
        return cls(
            email=e.email,
            github_pat_enc=e.github_pat_enc,
            kb_repo=e.kb_repo,
            kb_branch=e.kb_branch,
            mcp_token=e.mcp_token,
            created_at_unix=int(e.created_at.timestamp()),
        )

    def to_dict(self) -> dict:
        return self.__dict__


def from_entities(es: list[UserSetting]) -> list[UserSettingDTO]:
    return [UserSettingDTO.from_entity(e) for e in es]
