# Code generated by mss-protoc-gen. DO NOT EDIT.
from __future__ import annotations
from dataclasses import dataclass
from app.domain.entity.work_log import WorkLog


@dataclass
class WorkLogDTO:
    id: str
    project_id: str
    summary: str
    minutes: int
    source: str
    created_at_unix: int

    @classmethod
    def from_entity(cls, e: WorkLog) -> "WorkLogDTO":
        return cls(
            id=e.id,
            project_id=e.project_id,
            summary=e.summary,
            minutes=e.minutes,
            source=e.source,
            created_at_unix=int(e.created_at.timestamp()),
        )

    def to_dict(self) -> dict:
        return self.__dict__


def from_entities(es: list[WorkLog]) -> list[WorkLogDTO]:
    return [WorkLogDTO.from_entity(e) for e in es]
