// Code generated by mss-protoc-gen. DO NOT EDIT.

import { TaskForm } from "../../../gen/ui/task/TaskForm";
import { Page } from "../../../lib/widgets";

export default function NewTaskPage() {
  return (<Page title="New Task"><TaskForm /></Page>);
}
