// Code generated by mss-protoc-gen. DO NOT EDIT.

import { WorkLogForm } from "../../../../gen/ui/work_log/WorkLogForm";
import { Page } from "../../../../lib/widgets";

export default function EditWorkLogPage({ params }: { params: { id: string } }) {
  return (<Page title="Edit WorkLog"><WorkLogForm id={params.id} /></Page>);
}
