// Code generated by mss-protoc-gen. DO NOT EDIT.

import { WorkLogForm } from "../../../../gen/ui/work_log/WorkLogForm";

export default function EditWorkLogPage({ params }: { params: { id: string } }) {
  return (<main style={{ maxWidth: 640, margin: "2rem auto", fontFamily: "system-ui" }}><h1>Edit WorkLog</h1><WorkLogForm id={params.id} /></main>);
}
