# Code generated by mss-protoc-gen. DO NOT EDIT.
from __future__ import annotations
from datetime import datetime  # noqa: F401
from sqlalchemy import String, BigInteger, Integer, Boolean, Float, DateTime  # noqa: F401
from sqlalchemy.orm import Mapped, mapped_column
from app.domain.entity.base import Base


class Project(Base):
    __tablename__ = "projects"

    id: Mapped[str] = mapped_column(String(255), primary_key=True)
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    goal: Mapped[str] = mapped_column(String(255), nullable=True)
    status: Mapped[str] = mapped_column(String(255), nullable=False)
    progress: Mapped[int] = mapped_column(Integer, nullable=True)
    repo_url: Mapped[str] = mapped_column(String(255), nullable=True)
    kb_node: Mapped[str] = mapped_column(String(255), nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=True)

    @classmethod
    def new(cls, id: str, name: str, goal: str, status: str, progress: int, repo_url: str, kb_node: str, created_at: datetime) -> "Project":
        # 生成された validation(@pk / @required / @email)
        if not id:
            raise ValueError("id is required")
        name = (name or "").strip()
        if not name:
            raise ValueError("name is required")
        status = (status or "").strip()
        if not status:
            raise ValueError("status is required")
        return cls(id=id, name=name, goal=goal, status=status, progress=progress, repo_url=repo_url, kb_node=kb_node, created_at=created_at)
