# Code generated by mss-protoc-gen. DO NOT EDIT.
from __future__ import annotations
from app.domain.entity.project import Project
from app.domain.entity.work_log import WorkLog

# migration-gen が参照する全 Entity。
ALL = [Project, WorkLog]
