# Code generated by mss-protoc-gen. DO NOT EDIT.
from __future__ import annotations
from datetime import datetime  # noqa: F401
from sqlalchemy import String, BigInteger, Integer, Boolean, Float, DateTime  # noqa: F401
from sqlalchemy.orm import Mapped, mapped_column
from app.domain.entity.base import Base


class Task(Base):
    __tablename__ = "tasks"

    id: Mapped[str] = mapped_column(String(255), primary_key=True)
    project_id: Mapped[str] = mapped_column(String(255), nullable=False)
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    status: Mapped[str] = mapped_column(String(255), nullable=False)
    note: Mapped[str] = mapped_column(String(255), nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)

    @classmethod
    def new(cls, id: str, project_id: str, title: str, status: str, note: str, created_at: datetime) -> "Task":
        # 生成された validation(@pk / @required / @email)
        if not id:
            raise ValueError("id is required")
        project_id = (project_id or "").strip()
        if not project_id:
            raise ValueError("project_id is required")
        title = (title or "").strip()
        if not title:
            raise ValueError("title is required")
        status = (status or "").strip()
        if not status:
            raise ValueError("status is required")
        return cls(id=id, project_id=project_id, title=title, status=status, note=note, created_at=created_at)
