# Code generated by mss-protoc-gen. DO NOT EDIT.
from __future__ import annotations
from datetime import datetime  # noqa: F401
from sqlalchemy import String, BigInteger, Integer, Boolean, Float, DateTime  # noqa: F401
from sqlalchemy.orm import Mapped, mapped_column
from app.domain.entity.base import Base


class UserSetting(Base):
    __tablename__ = "user_settings"

    email: Mapped[str] = mapped_column(String(255), primary_key=True)
    github_pat_enc: Mapped[str] = mapped_column(String(255), nullable=True)
    kb_repo: Mapped[str] = mapped_column(String(255), nullable=False)
    kb_branch: Mapped[str] = mapped_column(String(255), nullable=True)
    mcp_token: Mapped[str] = mapped_column(String(255), nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=True)
    # @owned: 所有者(principal)。クライアントは触れず、repo が current_owner() で自動充填/絞り込みする。
    owner_email: Mapped[str | None] = mapped_column(String(255), nullable=True)

    @classmethod
    def new(cls, email: str, github_pat_enc: str, kb_repo: str, kb_branch: str, mcp_token: str, created_at: datetime) -> "UserSetting":
        # 生成された validation(@pk / @required / @email)
        if not email:
            raise ValueError("email is required")
        kb_repo = (kb_repo or "").strip()
        if not kb_repo:
            raise ValueError("kb_repo is required")
        return cls(email=email, github_pat_enc=github_pat_enc, kb_repo=kb_repo, kb_branch=kb_branch, mcp_token=mcp_token, created_at=created_at)
