# Code generated by mss-protoc-gen. DO NOT EDIT.
from __future__ import annotations
from datetime import datetime  # noqa: F401
from sqlalchemy import String, BigInteger, Integer, Boolean, Float, DateTime  # noqa: F401
from sqlalchemy.orm import Mapped, mapped_column
from app.domain.entity.base import Base


class WorkLog(Base):
    __tablename__ = "work_logs"

    id: Mapped[str] = mapped_column(String(255), primary_key=True)
    project_id: Mapped[str] = mapped_column(String(255), nullable=False)
    summary: Mapped[str] = mapped_column(String(255), nullable=False)
    detail: Mapped[str] = mapped_column(String(255), nullable=True)
    minutes: Mapped[int] = mapped_column(Integer, nullable=True)
    source: Mapped[str] = mapped_column(String(255), nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=True)

    @classmethod
    def new(cls, id: str, project_id: str, summary: str, detail: str, minutes: int, source: str, created_at: datetime) -> "WorkLog":
        # 生成された validation(@pk / @required / @email)
        if not id:
            raise ValueError("id is required")
        project_id = (project_id or "").strip()
        if not project_id:
            raise ValueError("project_id is required")
        summary = (summary or "").strip()
        if not summary:
            raise ValueError("summary is required")
        return cls(id=id, project_id=project_id, summary=summary, detail=detail, minutes=minutes, source=source, created_at=created_at)
