# Code generated by mss-protoc-gen. DO NOT EDIT.
from __future__ import annotations
from sqlalchemy import select, delete as sql_delete
from sqlalchemy.dialects.postgresql import insert as pg_insert
from sqlalchemy.exc import IntegrityError
from app.infra.db import tx
from app.domain.entity.project import Project
from app.domain.repository.project_repository import (
    ProjectNotFoundError,
    ProjectAlreadyExistsError,
)


class PostgresProjectRepository:
    def select_all(self) -> list[Project]:
        return list(tx.session().scalars(select(Project)).all())

    def select_by_pk(self, id) -> Project | None:
        return tx.session().get(Project, id)

    def insert(self, e: Project) -> None:
        s = tx.session()
        s.add(e)
        try:
            s.flush()
        except IntegrityError as ex:
            raise ProjectAlreadyExistsError() from ex

    def bulk_insert(self, es: list[Project]) -> None:
        if not es:
            return
        s = tx.session()
        s.add_all(es)
        try:
            s.flush()
        except IntegrityError as ex:
            raise ProjectAlreadyExistsError() from ex

    def upsert(self, e: Project) -> None:
        self._upsert([e])

    def bulk_upsert(self, es: list[Project]) -> None:
        if es:
            self._upsert(es)

    def _upsert(self, es: list[Project]) -> None:
        cols = ['id', 'name', 'goal', 'status', 'progress', 'repo_url', 'kb_node', 'created_at']
        vals = [{c: getattr(e, c) for c in cols} for e in es]
        stmt = pg_insert(Project).values(vals)
        upd = {c: getattr(stmt.excluded, c) for c in cols if c != "id"}
        tx.session().execute(
            stmt.on_conflict_do_update(index_elements=["id"], set_=upd)
        )

    def update(self, e: Project) -> None:
        s = tx.session()
        obj = s.get(Project, e.id)
        if obj is None:
            raise ProjectNotFoundError()
        obj.name = e.name
        obj.goal = e.goal
        obj.status = e.status
        obj.progress = e.progress
        obj.repo_url = e.repo_url
        obj.kb_node = e.kb_node
        obj.created_at = e.created_at
        s.flush()

    def delete(self, id) -> None:
        s = tx.session()
        obj = s.get(Project, id)
        if obj is None:
            raise ProjectNotFoundError()
        s.delete(obj)
        s.flush()

    def bulk_delete(self, ids) -> None:
        if not ids:
            return
        res = tx.session().execute(sql_delete(Project).where(Project.id.in_(ids)))
        if res.rowcount != len(ids):
            raise ProjectNotFoundError()

    def delete_all(self) -> None:
        tx.session().execute(sql_delete(Project))

    def select_by_cursor(self, limit, after) -> list[Project]:
        q = select(Project).order_by(Project.id).limit(limit)
        if after is not None:
            q = q.where(Project.id > after)
        return list(tx.session().scalars(q).all())


def new_postgres_project_repository() -> PostgresProjectRepository:
    return PostgresProjectRepository()


def auto_migrate_project(engine) -> None:
    Project.__table__.create(bind=engine, checkfirst=True)
