# Code generated by mss-protoc-gen. DO NOT EDIT.
from __future__ import annotations
from sqlalchemy import select, delete as sql_delete
from sqlalchemy.dialects.postgresql import insert as pg_insert
from sqlalchemy.exc import IntegrityError
from app.infra.db import tx
from app.infra.tenancy import current_owner
from app.domain.entity.project import Project
from app.domain.repository.project_repository import (
    ProjectNotFoundError,
    ProjectAlreadyExistsError,
)


class PostgresProjectRepository:
    # @owned: 全クエリを principal(owner_email)で絞り、他テナントの行に触れさせない(横断seam)。
    def select_all(self) -> list[Project]:
        q = select(Project)
        q = q.where(Project.owner_email == current_owner())
        return list(tx.session().scalars(q).all())

    def select_by_pk(self, id) -> Project | None:
        q = select(Project).where(Project.id == id, Project.owner_email == current_owner())
        return tx.session().scalars(q).first()

    def insert(self, e: Project) -> None:
        s = tx.session()
        e.owner_email = current_owner()
        s.add(e)
        try:
            s.flush()
        except IntegrityError as ex:
            raise ProjectAlreadyExistsError() from ex

    def bulk_insert(self, es: list[Project]) -> None:
        if not es:
            return
        s = tx.session()
        _owner = current_owner()
        for e in es:
            e.owner_email = _owner
        s.add_all(es)
        try:
            s.flush()
        except IntegrityError as ex:
            raise ProjectAlreadyExistsError() from ex

    def upsert(self, e: Project) -> None:
        self._upsert([e])

    def bulk_upsert(self, es: list[Project]) -> None:
        if es:
            self._upsert(es)

    def _upsert(self, es: list[Project]) -> None:
        cols = ['id', 'name', 'goal', 'status', 'progress', 'repo_url', 'kb_node', 'created_at'] + ["owner_email"]
        _owner = current_owner()
        for e in es:
            e.owner_email = _owner
        vals = [{c: getattr(e, c) for c in cols} for e in es]
        stmt = pg_insert(Project).values(vals)
        upd = {c: getattr(stmt.excluded, c) for c in cols if c != "id"}
        # 他テナントの行を上書きしない(pk衝突でも owner 不一致なら更新対象外にする conflict 条件)
        stmt = stmt.on_conflict_do_update(index_elements=["id"], set_=upd, where=(Project.owner_email == _owner))
        tx.session().execute(stmt)

    def update(self, e: Project) -> None:
        s = tx.session()
        obj = s.scalars(select(Project).where(Project.id == e.id, Project.owner_email == current_owner())).first()
        if obj is None:
            raise ProjectNotFoundError()
        obj.name = e.name
        obj.goal = e.goal
        obj.status = e.status
        obj.progress = e.progress
        obj.repo_url = e.repo_url
        obj.kb_node = e.kb_node
        obj.created_at = e.created_at
        s.flush()

    def delete(self, id) -> None:
        s = tx.session()
        obj = s.scalars(select(Project).where(Project.id == id, Project.owner_email == current_owner())).first()
        if obj is None:
            raise ProjectNotFoundError()
        s.delete(obj)
        s.flush()

    def bulk_delete(self, ids) -> None:
        if not ids:
            return
        stmt = sql_delete(Project).where(Project.id.in_(ids), Project.owner_email == current_owner())
        res = tx.session().execute(stmt)
        if res.rowcount != len(ids):
            raise ProjectNotFoundError()

    def delete_all(self) -> None:
        tx.session().execute(sql_delete(Project).where(Project.owner_email == current_owner()))

    def select_by_cursor(self, limit, after) -> list[Project]:
        q = select(Project).order_by(Project.id).limit(limit)
        q = q.where(Project.owner_email == current_owner())
        if after is not None:
            q = q.where(Project.id > after)
        return list(tx.session().scalars(q).all())


def new_postgres_project_repository() -> PostgresProjectRepository:
    return PostgresProjectRepository()


def auto_migrate_project(engine) -> None:
    Project.__table__.create(bind=engine, checkfirst=True)
