# Code generated by mss-protoc-gen. DO NOT EDIT.
from __future__ import annotations
from sqlalchemy import select, delete as sql_delete
from sqlalchemy.dialects.postgresql import insert as pg_insert
from sqlalchemy.exc import IntegrityError
from app.infra.db import tx
from app.domain.entity.task import Task
from app.domain.repository.task_repository import (
    TaskNotFoundError,
    TaskAlreadyExistsError,
)


class PostgresTaskRepository:
    def select_all(self) -> list[Task]:
        return list(tx.session().scalars(select(Task)).all())

    def select_by_pk(self, id) -> Task | None:
        return tx.session().get(Task, id)

    def insert(self, e: Task) -> None:
        s = tx.session()
        s.add(e)
        try:
            s.flush()
        except IntegrityError as ex:
            raise TaskAlreadyExistsError() from ex

    def bulk_insert(self, es: list[Task]) -> None:
        if not es:
            return
        s = tx.session()
        s.add_all(es)
        try:
            s.flush()
        except IntegrityError as ex:
            raise TaskAlreadyExistsError() from ex

    def upsert(self, e: Task) -> None:
        self._upsert([e])

    def bulk_upsert(self, es: list[Task]) -> None:
        if es:
            self._upsert(es)

    def _upsert(self, es: list[Task]) -> None:
        cols = ['id', 'project_id', 'title', 'status', 'note', 'created_at']
        vals = [{c: getattr(e, c) for c in cols} for e in es]
        stmt = pg_insert(Task).values(vals)
        upd = {c: getattr(stmt.excluded, c) for c in cols if c != "id"}
        tx.session().execute(
            stmt.on_conflict_do_update(index_elements=["id"], set_=upd)
        )

    def update(self, e: Task) -> None:
        s = tx.session()
        obj = s.get(Task, e.id)
        if obj is None:
            raise TaskNotFoundError()
        obj.project_id = e.project_id
        obj.title = e.title
        obj.status = e.status
        obj.note = e.note
        obj.created_at = e.created_at
        s.flush()

    def delete(self, id) -> None:
        s = tx.session()
        obj = s.get(Task, id)
        if obj is None:
            raise TaskNotFoundError()
        s.delete(obj)
        s.flush()

    def bulk_delete(self, ids) -> None:
        if not ids:
            return
        res = tx.session().execute(sql_delete(Task).where(Task.id.in_(ids)))
        if res.rowcount != len(ids):
            raise TaskNotFoundError()

    def delete_all(self) -> None:
        tx.session().execute(sql_delete(Task))

    def select_by_cursor(self, limit, after) -> list[Task]:
        q = select(Task).order_by(Task.id).limit(limit)
        if after is not None:
            q = q.where(Task.id > after)
        return list(tx.session().scalars(q).all())


def new_postgres_task_repository() -> PostgresTaskRepository:
    return PostgresTaskRepository()


def auto_migrate_task(engine) -> None:
    Task.__table__.create(bind=engine, checkfirst=True)
