# Code generated by mss-protoc-gen. DO NOT EDIT.
from __future__ import annotations
from sqlalchemy import select, delete as sql_delete
from sqlalchemy.dialects.postgresql import insert as pg_insert
from sqlalchemy.exc import IntegrityError
from app.infra.db import tx
from app.infra.tenancy import current_owner
from app.domain.entity.task import Task
from app.domain.repository.task_repository import (
    TaskNotFoundError,
    TaskAlreadyExistsError,
)


class PostgresTaskRepository:
    # @owned: 全クエリを principal(owner_email)で絞り、他テナントの行に触れさせない(横断seam)。
    def select_all(self) -> list[Task]:
        q = select(Task)
        q = q.where(Task.owner_email == current_owner())
        return list(tx.session().scalars(q).all())

    def select_by_pk(self, id) -> Task | None:
        q = select(Task).where(Task.id == id, Task.owner_email == current_owner())
        return tx.session().scalars(q).first()

    def insert(self, e: Task) -> None:
        s = tx.session()
        e.owner_email = current_owner()
        s.add(e)
        try:
            s.flush()
        except IntegrityError as ex:
            raise TaskAlreadyExistsError() from ex

    def bulk_insert(self, es: list[Task]) -> None:
        if not es:
            return
        s = tx.session()
        _owner = current_owner()
        for e in es:
            e.owner_email = _owner
        s.add_all(es)
        try:
            s.flush()
        except IntegrityError as ex:
            raise TaskAlreadyExistsError() from ex

    def upsert(self, e: Task) -> None:
        self._upsert([e])

    def bulk_upsert(self, es: list[Task]) -> None:
        if es:
            self._upsert(es)

    def _upsert(self, es: list[Task]) -> None:
        cols = ['id', 'project_id', 'title', 'status', 'note', 'created_at'] + ["owner_email"]
        _owner = current_owner()
        for e in es:
            e.owner_email = _owner
        vals = [{c: getattr(e, c) for c in cols} for e in es]
        stmt = pg_insert(Task).values(vals)
        upd = {c: getattr(stmt.excluded, c) for c in cols if c != "id"}
        # 他テナントの行を上書きしない(pk衝突でも owner 不一致なら更新対象外にする conflict 条件)
        stmt = stmt.on_conflict_do_update(index_elements=["id"], set_=upd, where=(Task.owner_email == _owner))
        tx.session().execute(stmt)

    def update(self, e: Task) -> None:
        s = tx.session()
        obj = s.scalars(select(Task).where(Task.id == e.id, Task.owner_email == current_owner())).first()
        if obj is None:
            raise TaskNotFoundError()
        obj.project_id = e.project_id
        obj.title = e.title
        obj.status = e.status
        obj.note = e.note
        obj.created_at = e.created_at
        s.flush()

    def delete(self, id) -> None:
        s = tx.session()
        obj = s.scalars(select(Task).where(Task.id == id, Task.owner_email == current_owner())).first()
        if obj is None:
            raise TaskNotFoundError()
        s.delete(obj)
        s.flush()

    def bulk_delete(self, ids) -> None:
        if not ids:
            return
        stmt = sql_delete(Task).where(Task.id.in_(ids), Task.owner_email == current_owner())
        res = tx.session().execute(stmt)
        if res.rowcount != len(ids):
            raise TaskNotFoundError()

    def delete_all(self) -> None:
        tx.session().execute(sql_delete(Task).where(Task.owner_email == current_owner()))

    def select_by_cursor(self, limit, after) -> list[Task]:
        q = select(Task).order_by(Task.id).limit(limit)
        q = q.where(Task.owner_email == current_owner())
        if after is not None:
            q = q.where(Task.id > after)
        return list(tx.session().scalars(q).all())


def new_postgres_task_repository() -> PostgresTaskRepository:
    return PostgresTaskRepository()


def auto_migrate_task(engine) -> None:
    Task.__table__.create(bind=engine, checkfirst=True)
