# Code generated by mss-protoc-gen. DO NOT EDIT.
from __future__ import annotations
from sqlalchemy import select, delete as sql_delete
from sqlalchemy.dialects.postgresql import insert as pg_insert
from sqlalchemy.exc import IntegrityError
from app.infra.db import tx
from app.infra.tenancy import current_owner
from app.domain.entity.user_setting import UserSetting
from app.domain.repository.user_setting_repository import (
    UserSettingNotFoundError,
    UserSettingAlreadyExistsError,
)


class PostgresUserSettingRepository:
    # @owned: 全クエリを principal(owner_email)で絞り、他テナントの行に触れさせない(横断seam)。
    def select_all(self) -> list[UserSetting]:
        q = select(UserSetting)
        q = q.where(UserSetting.owner_email == current_owner())
        return list(tx.session().scalars(q).all())

    def select_by_pk(self, email) -> UserSetting | None:
        q = select(UserSetting).where(UserSetting.email == email, UserSetting.owner_email == current_owner())
        return tx.session().scalars(q).first()

    def insert(self, e: UserSetting) -> None:
        s = tx.session()
        e.owner_email = current_owner()
        s.add(e)
        try:
            s.flush()
        except IntegrityError as ex:
            raise UserSettingAlreadyExistsError() from ex

    def bulk_insert(self, es: list[UserSetting]) -> None:
        if not es:
            return
        s = tx.session()
        _owner = current_owner()
        for e in es:
            e.owner_email = _owner
        s.add_all(es)
        try:
            s.flush()
        except IntegrityError as ex:
            raise UserSettingAlreadyExistsError() from ex

    def upsert(self, e: UserSetting) -> None:
        self._upsert([e])

    def bulk_upsert(self, es: list[UserSetting]) -> None:
        if es:
            self._upsert(es)

    def _upsert(self, es: list[UserSetting]) -> None:
        cols = ['email', 'github_pat_enc', 'kb_repo', 'kb_branch', 'mcp_token', 'created_at'] + ["owner_email"]
        _owner = current_owner()
        for e in es:
            e.owner_email = _owner
        vals = [{c: getattr(e, c) for c in cols} for e in es]
        stmt = pg_insert(UserSetting).values(vals)
        upd = {c: getattr(stmt.excluded, c) for c in cols if c != "email"}
        # 他テナントの行を上書きしない(pk衝突でも owner 不一致なら更新対象外にする conflict 条件)
        stmt = stmt.on_conflict_do_update(index_elements=["email"], set_=upd, where=(UserSetting.owner_email == _owner))
        tx.session().execute(stmt)

    def update(self, e: UserSetting) -> None:
        s = tx.session()
        obj = s.scalars(select(UserSetting).where(UserSetting.email == e.email, UserSetting.owner_email == current_owner())).first()
        if obj is None:
            raise UserSettingNotFoundError()
        obj.github_pat_enc = e.github_pat_enc
        obj.kb_repo = e.kb_repo
        obj.kb_branch = e.kb_branch
        obj.mcp_token = e.mcp_token
        obj.created_at = e.created_at
        s.flush()

    def delete(self, email) -> None:
        s = tx.session()
        obj = s.scalars(select(UserSetting).where(UserSetting.email == email, UserSetting.owner_email == current_owner())).first()
        if obj is None:
            raise UserSettingNotFoundError()
        s.delete(obj)
        s.flush()

    def bulk_delete(self, ids) -> None:
        if not ids:
            return
        stmt = sql_delete(UserSetting).where(UserSetting.email.in_(ids), UserSetting.owner_email == current_owner())
        res = tx.session().execute(stmt)
        if res.rowcount != len(ids):
            raise UserSettingNotFoundError()

    def delete_all(self) -> None:
        tx.session().execute(sql_delete(UserSetting).where(UserSetting.owner_email == current_owner()))


def new_postgres_user_setting_repository() -> PostgresUserSettingRepository:
    return PostgresUserSettingRepository()


def auto_migrate_user_setting(engine) -> None:
    UserSetting.__table__.create(bind=engine, checkfirst=True)
