# Code generated by mss-protoc-gen. DO NOT EDIT.
from __future__ import annotations
from sqlalchemy import select, delete as sql_delete
from sqlalchemy.dialects.postgresql import insert as pg_insert
from sqlalchemy.exc import IntegrityError
from app.infra.db import tx
from app.infra.tenancy import current_owner
from app.domain.entity.work_log import WorkLog
from app.domain.repository.work_log_repository import (
    WorkLogNotFoundError,
    WorkLogAlreadyExistsError,
)


class PostgresWorkLogRepository:
    # @owned: 全クエリを principal(owner_email)で絞り、他テナントの行に触れさせない(横断seam)。
    def select_all(self) -> list[WorkLog]:
        q = select(WorkLog)
        q = q.where(WorkLog.owner_email == current_owner())
        return list(tx.session().scalars(q).all())

    def select_by_pk(self, id) -> WorkLog | None:
        q = select(WorkLog).where(WorkLog.id == id, WorkLog.owner_email == current_owner())
        return tx.session().scalars(q).first()

    def insert(self, e: WorkLog) -> None:
        s = tx.session()
        e.owner_email = current_owner()
        s.add(e)
        try:
            s.flush()
        except IntegrityError as ex:
            raise WorkLogAlreadyExistsError() from ex

    def bulk_insert(self, es: list[WorkLog]) -> None:
        if not es:
            return
        s = tx.session()
        _owner = current_owner()
        for e in es:
            e.owner_email = _owner
        s.add_all(es)
        try:
            s.flush()
        except IntegrityError as ex:
            raise WorkLogAlreadyExistsError() from ex

    def upsert(self, e: WorkLog) -> None:
        self._upsert([e])

    def bulk_upsert(self, es: list[WorkLog]) -> None:
        if es:
            self._upsert(es)

    def _upsert(self, es: list[WorkLog]) -> None:
        cols = ['id', 'project_id', 'summary', 'detail', 'minutes', 'source', 'created_at'] + ["owner_email"]
        _owner = current_owner()
        for e in es:
            e.owner_email = _owner
        vals = [{c: getattr(e, c) for c in cols} for e in es]
        stmt = pg_insert(WorkLog).values(vals)
        upd = {c: getattr(stmt.excluded, c) for c in cols if c != "id"}
        # 他テナントの行を上書きしない(pk衝突でも owner 不一致なら更新対象外にする conflict 条件)
        stmt = stmt.on_conflict_do_update(index_elements=["id"], set_=upd, where=(WorkLog.owner_email == _owner))
        tx.session().execute(stmt)

    def update(self, e: WorkLog) -> None:
        s = tx.session()
        obj = s.scalars(select(WorkLog).where(WorkLog.id == e.id, WorkLog.owner_email == current_owner())).first()
        if obj is None:
            raise WorkLogNotFoundError()
        obj.project_id = e.project_id
        obj.summary = e.summary
        obj.detail = e.detail
        obj.minutes = e.minutes
        obj.source = e.source
        obj.created_at = e.created_at
        s.flush()

    def delete(self, id) -> None:
        s = tx.session()
        obj = s.scalars(select(WorkLog).where(WorkLog.id == id, WorkLog.owner_email == current_owner())).first()
        if obj is None:
            raise WorkLogNotFoundError()
        s.delete(obj)
        s.flush()

    def bulk_delete(self, ids) -> None:
        if not ids:
            return
        stmt = sql_delete(WorkLog).where(WorkLog.id.in_(ids), WorkLog.owner_email == current_owner())
        res = tx.session().execute(stmt)
        if res.rowcount != len(ids):
            raise WorkLogNotFoundError()

    def delete_all(self) -> None:
        tx.session().execute(sql_delete(WorkLog).where(WorkLog.owner_email == current_owner()))

    def select_by_cursor(self, limit, after) -> list[WorkLog]:
        q = select(WorkLog).order_by(WorkLog.id).limit(limit)
        q = q.where(WorkLog.owner_email == current_owner())
        if after is not None:
            q = q.where(WorkLog.id > after)
        return list(tx.session().scalars(q).all())


def new_postgres_work_log_repository() -> PostgresWorkLogRepository:
    return PostgresWorkLogRepository()


def auto_migrate_work_log(engine) -> None:
    WorkLog.__table__.create(bind=engine, checkfirst=True)
