# Code generated by mss-protoc-gen. DO NOT EDIT.
from __future__ import annotations
from sqlalchemy import select, delete as sql_delete
from sqlalchemy.dialects.postgresql import insert as pg_insert
from sqlalchemy.exc import IntegrityError
from app.infra.db import tx
from app.domain.entity.work_log import WorkLog
from app.domain.repository.work_log_repository import (
    WorkLogNotFoundError,
    WorkLogAlreadyExistsError,
)


class PostgresWorkLogRepository:
    def select_all(self) -> list[WorkLog]:
        return list(tx.session().scalars(select(WorkLog)).all())

    def select_by_pk(self, id) -> WorkLog | None:
        return tx.session().get(WorkLog, id)

    def insert(self, e: WorkLog) -> None:
        s = tx.session()
        s.add(e)
        try:
            s.flush()
        except IntegrityError as ex:
            raise WorkLogAlreadyExistsError() from ex

    def bulk_insert(self, es: list[WorkLog]) -> None:
        if not es:
            return
        s = tx.session()
        s.add_all(es)
        try:
            s.flush()
        except IntegrityError as ex:
            raise WorkLogAlreadyExistsError() from ex

    def upsert(self, e: WorkLog) -> None:
        self._upsert([e])

    def bulk_upsert(self, es: list[WorkLog]) -> None:
        if es:
            self._upsert(es)

    def _upsert(self, es: list[WorkLog]) -> None:
        cols = ['id', 'project_id', 'summary', 'detail', 'minutes', 'source', 'created_at']
        vals = [{c: getattr(e, c) for c in cols} for e in es]
        stmt = pg_insert(WorkLog).values(vals)
        upd = {c: getattr(stmt.excluded, c) for c in cols if c != "id"}
        tx.session().execute(
            stmt.on_conflict_do_update(index_elements=["id"], set_=upd)
        )

    def update(self, e: WorkLog) -> None:
        s = tx.session()
        obj = s.get(WorkLog, e.id)
        if obj is None:
            raise WorkLogNotFoundError()
        obj.project_id = e.project_id
        obj.summary = e.summary
        obj.detail = e.detail
        obj.minutes = e.minutes
        obj.source = e.source
        obj.created_at = e.created_at
        s.flush()

    def delete(self, id) -> None:
        s = tx.session()
        obj = s.get(WorkLog, id)
        if obj is None:
            raise WorkLogNotFoundError()
        s.delete(obj)
        s.flush()

    def bulk_delete(self, ids) -> None:
        if not ids:
            return
        res = tx.session().execute(sql_delete(WorkLog).where(WorkLog.id.in_(ids)))
        if res.rowcount != len(ids):
            raise WorkLogNotFoundError()

    def delete_all(self) -> None:
        tx.session().execute(sql_delete(WorkLog))

    def select_by_cursor(self, limit, after) -> list[WorkLog]:
        q = select(WorkLog).order_by(WorkLog.id).limit(limit)
        if after is not None:
            q = q.where(WorkLog.id > after)
        return list(tx.session().scalars(q).all())


def new_postgres_work_log_repository() -> PostgresWorkLogRepository:
    return PostgresWorkLogRepository()


def auto_migrate_work_log(engine) -> None:
    WorkLog.__table__.create(bind=engine, checkfirst=True)
